///////////////////////////////////////////////////////////////////////////////
//
//! \file date.hpp
//! Contains the \ref tag::autogenerate \ref ColumnTag type, the \ref is_autogenerate<>
//! metafunction and the \ref cryo::autogenerate<> \ref FieldDecorator type.
//
//  Copyright (c) 2010 dizzy
//
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
///////////////////////////////////////////////////////////////////////////////

#if !defined( CRYO_SCHEMA_TAG_AUTOGENERATE_HPP )
#define CRYO_SCHEMA_TAG_AUTOGENERATE_HPP

#include <cryo/cryo_fwd.hpp>
#include <cryo/schema/introspect/has_tag.hpp>
#include <cryo/schema/tag/wrapper.hpp>

namespace cryo
{
    namespace tag
    {
        //! \brief A \ref ColumnTag that marks the the column it is associated with as a
        //!        one whose value is generated by the database, if not specified when
        //!        inserting.
        //!
        //! \remark The type of field this tag is allowed to be associated with depends
        //!         on the specific backend implementation.
        struct autogenerate {};
    }

    //! \brief Metafunction that determines if a column has been tagged with the
    //!        \ref tag::autogenerate tag type.
    //!
    //! \tparam C A \ref PartialColumnDescriptor describing the table column that is to
    //!           be checked.
    template <typename C>
    struct is_autogenerate
        : has_tag<C, tag::autogenerate>
    {};

    //! \brief A \ref FieldDecorator that associates an entity field with the
    //!        \ref tag::autogenerate tag type.
    //!
    //! This metafunction returns a type that wraps the supplied type \c T. The
    //! wrapped type will behave in exactly the same way as the supplied type.
    //!
    //! \tparam T the field type to be wrapped.
    template <typename T>
    struct autogenerate
        : make_wrapper<T, tag::autogenerate>
    {};
}

#endif // #if !defined( CRYO_SCHEMA_TAG_AUTOGENERATE_HPP )
